# Generated by Django 5.1.6 on 2025-04-30 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointmentslot_delete_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentslot',
            name='reason_for_visit',
        ),
    ]
