# Generated by Django 5.1.6 on 2025-04-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='admit_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
