# Generated by Django 5.1.6 on 2025-04-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='cabinet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
